version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --port 6379
    hostname: redis
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - 6379:6379

  backend:
    image: backend
    container_name: backend
    build: ./backend/
    ports:
      - 8080:8080
    networks:
      - snacks-network
    depends_on:
      - redis

  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend/
    ports:
      - 3001:3001
    networks:
      - snacks-network

    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  snacks-network:
